### ISSUE TITLE
Doesn’t work for newer versions

### ISSUE THREAD

**Issue by MrRobotjs** [ipatate/gatsby-plugin-snipcart-advanced#6]
This plugin and as most Snipcart plugins don’t work with Gatsby anymore. From what I can tell, any version about 3.0.6 will not work in Gatsby. Unless I’m doing this wrong please find a fix as this isn’t really usable with the default values.

**Comment by Igor178** [comment]
@MrRobotjs yes the latest version doesn't work. I'm using the default which is 3.0.15 and it works fine for now.

**Comment by osseonews** [comment]
Curious why this doens't work on versions above 3.0.6? What changed in snipcart to make this plugin not work?

**Comment by ipatate** [comment]
I look that soon

**Comment by osseonews** [comment]
Thanks. That would be great.

**Comment by MrRobotjs** [comment]
Any update? None of the plug-ins support new versions which is a huge issue. 3.0.28 fixes an issue where users weren’t able to reset their password because the “forgot your password?” didn’t exist. I’d look into it myself but I’m sadly not experienced enough to tackle this issue.

**Comment by ipatate** [comment]
i have test just now the 3.0.28 version and i haven't problem. What bug have you ?
