### ISSUE TITLE
Section customization 

### ISSUE THREAD

**Issue by rethc** [ipatate/gatsby-plugin-snipcart-advanced#7]
Hi, I am new to Gatsby and I am having trouble customizing the sections using the innerHTML plugin options.

I am wanting to add a header and add top-margin or padding in the header. I had a look at the Snipcart document but it was a bit hard to understand.

![snipcart-screenshot](https://user-images.githubusercontent.com/2496736/103645887-9a3c7a00-4fbd-11eb-9e63-6b03e9eeeeb0.png)

Options:

```js
innerHTML: '
	<checkout section="header" style="padding-top: 200px;">
	<cart-header>
	<h1>Test header</h1>
	</cart-header>
	</checkout>''
```

**Comment by ipatate** [comment]
hello, for adding margin or padding use just CSS in your global CSS file project. Target the class ".snipcart-cart-header__title" by example and add your properties.

**Comment by rethc** [comment]
> hello, for adding margin or padding use just CSS in your global CSS file project. Target the class ".snipcart-cart-header__title" by example and add your properties.

Thanks, I tried this before but it didn't seem to work so I looked at your plugin. It's working now that I set the important property.
